import type { DeploymentStrategy, DeploymentTargetName } from "../domain/types.js";
export declare const SCHEMA_VERSION: 1;
export declare function getStateRoot(): string;
export type TargetDefinition = {
    label: string;
    strategy: DeploymentStrategy;
    envVar: string;
    writerKey: string;
    writeRootCandidates: string[];
    compatReadRootCandidates: string[];
};
export declare const TARGET_ORDER: DeploymentTargetName[];
export declare const TARGET_DEFINITIONS: Record<DeploymentTargetName, TargetDefinition>;
export declare const TARGET_LABELS: Record<DeploymentTargetName, string>;
export declare const TARGET_STRATEGIES: Record<DeploymentTargetName, DeploymentStrategy>;
export declare const TARGET_ENV_VARS: Record<DeploymentTargetName, string>;
export declare const TARGET_WRITER_KEYS: Record<DeploymentTargetName, string>;
export declare const TARGET_PATH_CANDIDATES: Record<DeploymentTargetName, string[]>;
export declare const TARGET_COMPAT_READ_CANDIDATES: Record<DeploymentTargetName, string[]>;
export declare function getExplicitTargetNames(): DeploymentTargetName[];
export declare function isExplicitTargetMode(): boolean;
export declare function getTargetDetectionCandidates(target: DeploymentTargetName): string[];
export declare function getTargetScanRoots(target: DeploymentTargetName): string[];
